### ISSUE TITLE
add two functions

### ISSUE THREAD

**Issue by malefooo** [Yinet-project/marrow#24]
@Baoyuantop 

1. add judgment table exists or not, method definition `_sql_table_exist(ptr: number,size: number) -> i32`
2. add get timestamp,method definition `_get_timestamp()->i64`

**Comment by Baoyuantop** [comment]
what is the map of exists or not for i32 result?

**Comment by malefooo** [comment]
0 success
1 fail

**Comment by tiannian** [comment]
This issue seems close? 
@Baoyuantop @malefooo

**Comment by Baoyuantop** [comment]
ok, it's outdata
